# Copyright 2022 Jimmi Dyson
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socat-apiserver
  namespace: multicluster-demo
spec:
  selector:
    matchLabels:
      app: socat-apiserver
  replicas: 1
  template:
    metadata:
      annotations:
        kuma.io/mesh: multicluster
      labels:
        app: socat-apiserver
    spec:
      containers:
        - name: socat
          image: "alpine/socat:latest"
          args:
            - "TCP-LISTEN:8443,fork"
            - "TCP:kubernetes.default.svc:443"
          ports:
            - name: socat
              containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: socat-apiserver
  namespace: multicluster-demo
  annotations:
    443.service.kuma.io/protocol: tcp
spec:
  selector:
    app: socat-apiserver
  ports:
  - protocol: TCP
    port: 443
    targetPort: socat
