# Copyright 2022 Jimmi Dyson
# SPDX-License-Identifier: Apache-2.0

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
  - id: check-yaml
    args: ["-m", "--unsafe"]
    stages: [commit]
  - id: mixed-line-ending
    args: ["-f", "lf"]
    exclude: \.bat$
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  - id: check-case-conflict
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
  - id: check-symlinks
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: shfmt
    stages: [commit]
    args: ["-s", "-i", "2"]
  - id: script-must-have-extension
    stages: [commit]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.4
  hooks:
  - id: shellcheck
    stages: [commit]
    args: ["-x"]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
    stages: [commit]
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.12
  hooks:
  - id: insert-license
    name: License headers - shell scripts
    stages: [commit]
    files: \.sh$
    args:
      - --license-filepath
      - header.txt
      - --comment-style
      - '#'
  - id: insert-license
    name: License headers - Markdown
    stages: [commit]
    files: \.md$
    args:
      - --license-filepath
      - header.txt
      - --comment-style
      - <!--|| -->
  - id: insert-license
    name: License headers - YAML
    stages: [commit]
    files: \.yaml$
    args:
      - --license-filepath
      - header.txt
